version: '3'

dotenv: ['.env']

vars:
  YEAR:
    sh: date +%Y
  DAY:
    sh: date +%d
  DAY_PADDED:
    sh: "printf '%02d' \"$((10#{{.DAY}}))\""
  COLLECTION: -collection:aoc=./lib

tasks:
  run:
    desc: "Run a day's solution"
    cmds:
      - >
        odin run ./{{.YEAR}}/day{{.DAY_PADDED}}
        {{ .COLLECTION }}
        -- {{.CLI_ARGS}}

  bench:day:
    desc: "Benchmark a given day using hyperfine"
    cmds:
      - >
        odin build {{ .YEAR }}/day{{ .DAY_PADDED }}
        {{ .COLLECTION }}
        -out:./aocday-bench -o:speed
      - defer: rm ./aocday-bench
      - hyperfine -w 2 -N "./aocday-bench {{ .CLI_ARGS }}"

  bench:
    desc: "Compare all binaries in the bench folder"
    silent: true
    cmd: './scripts/bench-all.sh {{ .CLI_ARGS }}'

  bench:clean:
    desc: "Clean the bench directory"
    cmd: rm -r ./bench

  test:
    desc: "Run the tests for the aoclib"
    cmd: odin test ./tests -all-packages {{ .COLLECTION }} -vet -strict-style

  new:
    desc: "Scaffold a new day"
    status:
      - test -f ./{{.YEAR}}/day{{.DAY_PADDED}}/main.odin
    cmds:
      - ./scripts/new_day.sh {{.YEAR}} {{.DAY_PADDED}}
      - task: get

  get:
    desc: "Fetch puzzle input"
    vars:
      AOC_SESSION:
        secret: true
        sh: echo $AOC_SESSION
    status:
      - test -f ./inputs/{{.YEAR}}/{{.DAY_PADDED}}.in
    cmds:
       - ./scripts/fetch_input.sh {{.YEAR}} {{.DAY_PADDED}} {{.AOC_SESSION}}
